version: 2
working_directory: &working_directory ~/workspace

commands:
  run-ci:
    parameters:
      after-ci:
        description: 'Steps after CI'
        type: steps
        default: []

    steps:
      - checkout
      - restore_cache:
          key: rmc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Lerna Bootstrap
          command: npm run bootstrap
      - run:
          name: Build
          command: npm run ci
      - run:
          name: Report coverage
          command: npm run codecov
      - save_cache:
          key: rmc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - steps: << parameters.after-ci >>

base: &base
  working_directory: *working_directory
  docker:
    - image: circleci/node:12
  steps:
    - run-ci:
      after-ci:
        - run: 'echo "CI Complete"'

jobs:
  build_node_10:
    <<: *base
    docker:
      - image: circleci/node:10

  build_node_12:
    <<: *base
    docker:
      - image: circleci/node:12

  publish:
    <<: *base
    parameters:
      publish-branch:
        type: env_var_name
        default: master
    steps:
      - run-ci:
        after-ci:
          - run:
            name: Publish << parameters.publish-branch >>
            command: |
              set -o errexit
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              BRANCH=<< parameters.publish-branch >> node ./scripts/publish.js
          - run:
            name: Push to Github
            command: |
              git push -q "https://$GITHUB_TOKEN@github.com/doxiaodong/rmc.git" $(git rev-parse --abbrev-ref HEAD):<< parameters.publish-branch >>

workflows:
  version: 2
  build:
    jobs:
      - build_node_10
      - build_node_12

  release-alpha:
    jobs:
      - publish:
          publish-branch: alpha
          filters:
            branches:
              only:
                - alpha

  release:
    jobs:
      - publish:
          publish-branch: master
          filters:
            branches:
              only:
                - master
