version: 2.1
working_directory: &working_directory ~/workspace

base: &base
  working_directory: *working_directory
  docker:
    - image: circleci/node:12
  steps:
    - checkout
    - restore_cache:
        key: rmc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Install dependencies
        command: npm i
    - run:
        name: Lerna Bootstrap
        command: npm run bootstrap
    - run:
        name: Build
        command: npm run ci
    - run:
        name: Report coverage
        command: npm run codecov
    - save_cache:
        key: rmc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - 'node_modules'

jobs:
  build_node_10:
    <<: *base
    docker:
      - image: circleci/node:10

  build_node_12:
    <<: *base
    docker:
      - image: circleci/node:12

  publish_alpha:
    <<: *base

  publish:
    <<: *base

workflows:
  version: 2
  build:
    jobs:
      - build_node_10
      - build_node_12

  release-alpha:
    jobs:
      - publish_alpha:
          filters:
            branches:
              only:
                - alpha

  release:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
