version: 2
working_directory: &working_directory ~/workspace
base: &base
  working_directory: *working_directory
  docker:
    - image: circleci/node:10
  steps:
    - checkout
    - restore_cache:
        key: rmc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Install dependencies
        command: npm i
    - run:
        name: Lerna Bootstrap
        command: npm run bootstrap
    - run:
        name: Build
        command: npm run ci
    - run:
        name: Report coverage
        command: npm run codecov
    - save_cache:
        key: rmc-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - 'node_modules'

jobs:
  build_node_10:
    <<: *base
    docker:
      - image: circleci/node:10

  build_node_12:
    <<: *base
    docker:
      - image: circleci/node:12

  publish:
    docker:
      - image: circleci/node:10
    working_directory: *working_directory
    steps:
      - checkout
      - restore_cache:
          key: rmc-tag-master-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Lerna Bootstrap
          command: npm run bootstrap
      - run:
          name: Set git
          command: |
            git config --global user.name "circle-bot"
            git config --global user.email "duxiaodong@darlin.me"
      - run:
          name: Publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            CIRCLE_TAG=$CIRCLE_TAG node ./scripts/publish.js
      - run:
          name: Push to Github
          command: |
            git push -q "https://$GITHUB_TOKEN@github.com/doxiaodong/rmc.git" $(git rev-parse --abbrev-ref HEAD):master
            echo "Push success!!"
      - save_cache:
          key: rmc-tag-master-{{ checksum "package.json" }}
          paths:
            - 'node_modules'

workflows:
  version: 2
  build:
    jobs:
      - build_node_10
      - build_node_12

  tagged-build:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release:.*/
